/**
 * Reads one-time login codes from the Maildev inbox used by the E2E stack.
 *
 * The login OTP is a secure random 6-digit code generated by Better Auth and
 * delivered by email, so tests can no longer hardcode it. This helper polls the
 * Maildev HTTP API (`GET /email`) for the most recent message addressed to a
 * given recipient and extracts the code from its subject/text/html.
 *
 * Base URL defaults to `http://localhost:1080` and is overridable with
 * `MAILDEV_URL` (matching the CI service in `.github/workflows/e2e-tests.yml`).
 */

const MAILDEV_BASE_URL = process.env.MAILDEV_URL ?? 'http://localhost:1080';

type MaildevRecipient = { address?: string; name?: string };

type MaildevMessage = {
  id?: string;
  to?: MaildevRecipient[];
  subject?: string;
  text?: string;
  html?: string;
  date?: string;
  time?: string;
};

const OTP_PATTERN = /\b(\d{6})\b/;

export type MaildevOtpPollEvent = {
  type:
    | 'maildev.otp.found'
    | 'maildev.poll.error'
    | 'maildev.poll.result'
    | 'maildev.poll.timeout';
  details: {
    attempt: number;
    baseUrl: string;
    elapsedMs: number;
    afterGateEnabled: boolean;
    afterMs?: number;
    error?: string;
    latestAddressedMessageAt?: string;
    latestMessageAt?: string;
    messagesAddressedToRecipient?: number;
    messagesEligibleAfterGate?: number;
    messagesWithOtp?: number;
    status?: number;
    totalMessages?: number;
  };
};

type MaildevOtpPollExtraDetails = Partial<
  Omit<
    MaildevOtpPollEvent['details'],
    'afterGateEnabled' | 'afterMs' | 'attempt' | 'baseUrl' | 'elapsedMs'
  >
>;

const extractOtp = (message: MaildevMessage): string | undefined => {
  for (const source of [message.subject, message.text, message.html]) {
    const match = source?.match(OTP_PATTERN);
    if (match) return match[1];
  }
  return undefined;
};

const isAddressedTo = (
  message: MaildevMessage,
  email: null | string | undefined
) => {
  const normalizedEmail = email?.toLowerCase();
  if (!normalizedEmail) return false;

  return (message.to ?? []).some(
    (recipient) => recipient.address?.toLowerCase() === normalizedEmail
  );
};

const messageTimestamp = (message: MaildevMessage) => {
  const dateText = message.date ?? message.time;
  if (!dateText) return undefined;

  const timestamp = Date.parse(dateText);
  return Number.isNaN(timestamp) ? undefined : timestamp;
};

const isoTimestamp = (timestamp: number | undefined) =>
  timestamp === undefined ? undefined : new Date(timestamp).toISOString();

const formatUnknownError = (error: unknown): string => {
  if (error instanceof Error) return error.message;
  if (typeof error === 'string') return error;

  try {
    return JSON.stringify(error) ?? String(error);
  } catch {
    return String(error);
  }
};

const summarizeMessages = (
  messages: MaildevMessage[],
  input: { email: string; hasAfterGate: boolean; afterMs: number }
) => {
  let latestMessageAt: number | undefined;
  let latestAddressedMessageAt: number | undefined;

  const addressedMessages = messages.filter((message) => {
    const timestamp = messageTimestamp(message);
    if (
      timestamp !== undefined &&
      (latestMessageAt === undefined || timestamp > latestMessageAt)
    ) {
      latestMessageAt = timestamp;
    }

    const addressed = isAddressedTo(message, input.email);
    if (
      addressed &&
      timestamp !== undefined &&
      (latestAddressedMessageAt === undefined ||
        timestamp > latestAddressedMessageAt)
    ) {
      latestAddressedMessageAt = timestamp;
    }

    return addressed;
  });

  const eligibleMessages = addressedMessages.filter((message) => {
    const timestamp = messageTimestamp(message);
    return (
      !input.hasAfterGate ||
      (timestamp !== undefined && timestamp >= input.afterMs)
    );
  });

  return {
    latestAddressedMessageAt: isoTimestamp(latestAddressedMessageAt),
    latestMessageAt: isoTimestamp(latestMessageAt),
    messagesAddressedToRecipient: addressedMessages.length,
    messagesEligibleAfterGate: eligibleMessages.length,
    messagesWithOtp: eligibleMessages.filter((message) => extractOtp(message))
      .length,
    totalMessages: messages.length,
  };
};

const fetchMessages = async (): Promise<{
  messages: MaildevMessage[];
  status: number;
}> => {
  const response = await fetch(`${MAILDEV_BASE_URL}/email`);
  if (!response.ok) {
    throw new Error(`Maildev request failed with status ${response.status}`);
  }
  return {
    messages: (await response.json()) as MaildevMessage[],
    status: response.status,
  };
};

export const readLatestOtp = async (
  email: string,
  options: {
    afterMs?: number;
    intervalMs?: number;
    onPoll?: (event: MaildevOtpPollEvent) => void;
    timeoutMs?: number;
  } = {}
): Promise<string> => {
  const hasAfterGate = options.afterMs !== undefined;
  const afterMs = options.afterMs ?? 0;
  const timeoutMs = options.timeoutMs ?? 15_000;
  const intervalMs = options.intervalMs ?? 500;
  const deadline = Date.now() + timeoutMs;
  const startedAt = Date.now();

  let attempt = 0;
  let lastError: unknown;
  const basePollDetails = (): MaildevOtpPollEvent['details'] => ({
    attempt,
    baseUrl: MAILDEV_BASE_URL,
    elapsedMs: Date.now() - startedAt,
    afterGateEnabled: hasAfterGate,
    ...(hasAfterGate ? { afterMs } : {}),
  });
  const emitPoll = (
    type: MaildevOtpPollEvent['type'],
    details: MaildevOtpPollExtraDetails = {}
  ) => {
    options.onPoll?.({
      type,
      details: {
        ...basePollDetails(),
        ...details,
      },
    });
  };

  do {
    attempt += 1;
    try {
      const { messages, status } = await fetchMessages();
      const summary = summarizeMessages(messages, {
        afterMs,
        email,
        hasAfterGate,
      });
      emitPoll('maildev.poll.result', {
        ...summary,
        status,
      });

      const otp = messages
        .filter((message) => {
          const timestamp = messageTimestamp(message);
          return (
            isAddressedTo(message, email) &&
            (!hasAfterGate || (timestamp !== undefined && timestamp >= afterMs))
          );
        })
        .sort((a, b) => (messageTimestamp(b) ?? 0) - (messageTimestamp(a) ?? 0))
        .map(extractOtp)
        .find((value): value is string => Boolean(value));
      if (otp) {
        emitPoll('maildev.otp.found', {
          ...summary,
          status,
        });
        return otp;
      }
    } catch (error) {
      lastError = error;
      emitPoll('maildev.poll.error', {
        error: formatUnknownError(error),
      });
    }

    await new Promise((resolve) => setTimeout(resolve, intervalMs));
  } while (Date.now() < deadline);

  emitPoll(
    'maildev.poll.timeout',
    lastError
      ? {
          error: formatUnknownError(lastError),
        }
      : undefined
  );

  throw new Error(
    `Timed out after ${timeoutMs}ms waiting for an OTP email to ${email}` +
      (lastError ? `: ${formatUnknownError(lastError)}` : '')
  );
};
