/**
 * Reads one-time login codes from the Maildev inbox used by the E2E stack.
 *
 * The login OTP is a secure random 6-digit code generated by Better Auth and
 * delivered by email, so tests can no longer hardcode it. This helper polls the
 * Maildev HTTP API (`GET /email`) for the most recent message addressed to a
 * given recipient and extracts the code from its subject/text/html.
 *
 * Base URL defaults to `http://localhost:1080` and is overridable with
 * `MAILDEV_URL` (matching the CI service in `.github/workflows/e2e-tests.yml`).
 */

const MAILDEV_BASE_URL = process.env.MAILDEV_URL ?? 'http://localhost:1080';

type MaildevRecipient = { address?: string; name?: string };

type MaildevMessage = {
  id?: string;
  to?: MaildevRecipient[];
  subject?: string;
  text?: string;
  html?: string;
  date?: string;
  time?: string;
};

const OTP_PATTERN = /\b(\d{6})\b/;

const extractOtp = (message: MaildevMessage): string | undefined => {
  for (const source of [message.subject, message.text, message.html]) {
    const match = source?.match(OTP_PATTERN);
    if (match) return match[1];
  }
  return undefined;
};

const isAddressedTo = (
  message: MaildevMessage,
  email: null | string | undefined
) => {
  const normalizedEmail = email?.toLowerCase();
  if (!normalizedEmail) return false;

  return (message.to ?? []).some(
    (recipient) => recipient.address?.toLowerCase() === normalizedEmail
  );
};

const messageTimestamp = (message: MaildevMessage) => {
  const dateText = message.date ?? message.time;
  if (!dateText) return undefined;

  const timestamp = Date.parse(dateText);
  return Number.isNaN(timestamp) ? undefined : timestamp;
};

const fetchMessages = async (): Promise<MaildevMessage[]> => {
  const response = await fetch(`${MAILDEV_BASE_URL}/email`);
  if (!response.ok) {
    throw new Error(`Maildev request failed with status ${response.status}`);
  }
  return (await response.json()) as MaildevMessage[];
};

export const readLatestOtp = async (
  email: string,
  options: { afterMs?: number; timeoutMs?: number; intervalMs?: number } = {}
): Promise<string> => {
  const hasAfterGate = options.afterMs !== undefined;
  const afterMs = options.afterMs ?? 0;
  const timeoutMs = options.timeoutMs ?? 15_000;
  const intervalMs = options.intervalMs ?? 500;
  const deadline = Date.now() + timeoutMs;

  let lastError: unknown;
  do {
    try {
      const otp = (await fetchMessages())
        .filter((message) => {
          const timestamp = messageTimestamp(message);
          return (
            isAddressedTo(message, email) &&
            (!hasAfterGate || (timestamp !== undefined && timestamp >= afterMs))
          );
        })
        .sort((a, b) => (messageTimestamp(b) ?? 0) - (messageTimestamp(a) ?? 0))
        .map(extractOtp)
        .find((value): value is string => Boolean(value));
      if (otp) return otp;
    } catch (error) {
      lastError = error;
    }

    await new Promise((resolve) => setTimeout(resolve, intervalMs));
  } while (Date.now() < deadline);

  throw new Error(
    `Timed out after ${timeoutMs}ms waiting for an OTP email to ${email}` +
      (lastError ? `: ${String(lastError)}` : '')
  );
};
